apiVersion: v1
kind: Service
metadata:
  name : wp-mysql 
  labels:
    name: wordpress
  namespace: wordpress
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: wordpress
  type: ClusterIP
